name: Express CI/CD

on:
  push:
    branches:
      - main
      - prod

jobs:
  build-and-echo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Echo Environment
        run: echo "Environment: ${{ github.event_name }} branch: ${{ github.ref }}"

      # Add your additional build and test steps here

  deploy-to-dev:
    runs-on: ubuntu-latest
    
    needs: build-and-echo

    steps:
      - name: Deploy to Development
        run: echo "Deploying to development environment..."

      # Add your additional deployment steps here
